import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Clock3, Database, Eraser, History, LayoutDashboard, LogOut, RefreshCw, RotateCcw, Send, Upload } from 'lucide-react';
import { Dashboard } from './components/Dashboard'; import { ExecutiveOverview, type OverviewModuleData } from './components/ExecutiveOverview'; import { EmptyState } from './components/EmptyState'; import { UploadModal } from './components/UploadModal';
import { inspectWorkbook, UTILIZADO_SCHEMA_VERSION } from './services/workbook'; import { adminFetch, signIn, signOut, validSession } from './services/auth'; import type { DataRow, SourceModule, ValidationReport } from './types'; import './styles.css';

const modules: SourceModule[] = ['Utilizado', 'Faturado', 'Recebido'];
type Pending = { rows: DataRow[]; report: ValidationReport };
type ModuleResponse = { module: SourceModule; rows: DataRow[]; columns: string[]; report: ValidationReport; updated: string; versionId: string };
type ImportEntry = { id:string; module:SourceModule; file_name:string; created_at:string; published_at?:string; row_count:number; status:string; is_active:boolean; version_id:string; error_message?:string };

function Login() { const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); useEffect(()=>{ validSession().then(s=>{if(s) location.replace('/admin');}); },[]); const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await signIn(email,password);location.replace('/admin');}catch(reason){setError(reason instanceof Error?reason.message:'Não foi possível entrar.');setBusy(false);}}; return <main className="login-page"><form className="login-card" onSubmit={submit}><div className="brand-mark">UFR</div><p className="eyebrow">INTELIGÊNCIA EXECUTIVA</p><h1>Acesso administrativo</h1><p>Entre para atualizar, validar e publicar as bases.</p><label>E-mail<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error-box">{error}</div>}<button className="primary-button" disabled={busy}>{busy?'Entrando…':'Entrar'}</button><a href="/dashboard">Voltar ao dashboard</a></form></main>; }

export function App({ admin }: { admin:boolean }) {
 const [authorized,setAuthorized]=useState(!admin); const [moduleData,setModuleData]=useState<Partial<Record<SourceModule,OverviewModuleData>>>({}); const [activeModule,setActiveModule]=useState<SourceModule|'Visão Geral'>('Visão Geral'); const [activeUploadModule,setActiveUploadModule]=useState<SourceModule|null>(null); const [modal,setModal]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [pending,setPending]=useState<Pending|null>(null); const [sharedFilters,setSharedFilters]=useState<Record<string,string[]>>({}); const [resetSignal,setResetSignal]=useState(0); const [progress,setProgress]=useState<{current:number;total:number;sent:number;rows:number}|null>(null); const [history,setHistory]=useState<ImportEntry[]>([]); const [showHistory,setShowHistory]=useState(false); const [readyImport,setReadyImport]=useState<string|null>(null); const [notice,setNotice]=useState(''); const [versions,setVersions]=useState<Record<string,string>>({});
 useEffect(()=>{ if(admin) validSession().then(s=>{if(!s)location.replace('/login');else setAuthorized(true)}); },[admin]);
 const load=async(silent=false)=>{try{const results=await Promise.all(modules.map(async m=>{const r=await fetch(`/api?scope=dashboard&view=${m.toLowerCase()}`,{cache:'no-store'});if(!r.ok)throw new Error();return r.json() as Promise<ModuleResponse>})); const next: Partial<Record<SourceModule, OverviewModuleData>>={}; const nextVersions:Record<string,string>={}; results.forEach(item=>{if(item.rows.length){next[item.module]={rows:item.rows,columns:item.columns,report:item.report,updated:new Date(item.updated)};nextVersions[item.module]=item.versionId;}}); if(silent&&Object.keys(versions).some(k=>versions[k]&&versions[k]!==nextVersions[k]))setNotice('Uma nova versão dos dados está disponível.'); setVersions(nextVersions);setModuleData(next);}catch{setError('Não foi possível carregar os dados publicados.');}};
 // Loading is intentionally keyed to authorization; version polling owns subsequent refreshes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!authorized)return;load();const timer=setInterval(()=>load(true),60000);return()=>clearInterval(timer);},[authorized]);
 useEffect(()=>{const key='ufr-utilizado-schema';if(localStorage.getItem(key)!==UTILIZADO_SCHEMA_VERSION){localStorage.removeItem('ufr-active-filters');localStorage.setItem(key,UTILIZADO_SCHEMA_VERSION);setResetSignal(v=>v+1)}},[]);
 const chooseFile=async(file:File)=>{setError(null);if(!activeUploadModule)return setError('Selecione qual base deseja atualizar antes de escolher o arquivo.');setLoading(true);try{if(!file.name.toLowerCase().endsWith('.xlsx'))throw new Error('O formato do arquivo não é suportado. Selecione exclusivamente um arquivo .xlsx.');const inspected=await inspectWorkbook(file,activeUploadModule);setPending(inspected);}catch(reason){setError(reason instanceof Error?reason.message:'A importação não foi concluída. A versão anterior foi preservada.');}finally{setLoading(false)}};
 const request=async(path:string,body:unknown)=>{const r=await adminFetch(path,{method:'POST',body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Falha na importação.');return data;};
 const confirm=async()=>{if(!pending||loading)return;setLoading(true);setError(null);const size=750,total=Math.ceil(pending.rows.length/size);try{const start=await request('/api?scope=admin&action=start',{module:pending.report.module,fileName:pending.report.fileName,summary:pending.report,expectedBatches:total});for(let i=0;i<total;i++){const rows=pending.rows.slice(i*size,(i+1)*size);let last:unknown;for(let attempt=1;attempt<=3;attempt++){try{await request('/api?scope=admin&action=batch',{importId:start.importId,batchNumber:i+1,offset:i*size,rows});last=null;break}catch(e){last=e;if(attempt<3)await new Promise(r=>setTimeout(r,attempt*700));}}if(last)throw last;setProgress({current:i+1,total,sent:Math.min((i+1)*size,pending.rows.length),rows:pending.rows.length});}await request('/api?scope=admin&action=validate',{importId:start.importId});setReadyImport(start.importId);setNotice('Importação validada. Publique a atualização para disponibilizá-la.');setModal(false);setPending(null);await loadHistory();}catch(reason){setError(`${reason instanceof Error?reason.message:'Falha no envio'} A importação não foi concluída. A versão anterior foi preservada.`);}finally{setLoading(false);setProgress(null)}};
 const publish=async()=>{if(!readyImport)return;setLoading(true);try{const result=await request('/api?scope=admin&action=publish',{importId:readyImport});setNotice(result.message);setReadyImport(null);await load();await loadHistory();}catch(e){setError(e instanceof Error?e.message:'Falha ao publicar.')}finally{setLoading(false)}};
 const loadHistory=async()=>{const r=await adminFetch('/api?scope=admin&action=history');if(r.ok)setHistory(await r.json());}; const openHistory=()=>{setShowHistory(true);loadHistory()}; const restore=async(id:string)=>{if(loading)return;setLoading(true);try{await request('/api?scope=admin&action=restore',{importId:id});setNotice('Versão restaurada com sucesso.');await load();await loadHistory();}catch(e){setError(e instanceof Error?e.message:'Falha ao restaurar.')}finally{setLoading(false)}};
 if(!authorized)return <div className="route-loading">Validando sessão…</div>; const activeData=activeModule==='Visão Geral'?undefined:moduleData[activeModule]; const openUpload=(m:SourceModule|null=null)=>{setPending(null);setError(null);setActiveUploadModule(m);setModal(true)};
 return <div className="app-shell"><header><div className="brand-mark">UFR</div><div className="heading"><p>INTELIGÊNCIA EXECUTIVA</p><h1>Utilizado <i/> <span>Faturado</span> <i/> <span>Recebido</span></h1><h2>{activeModule==='Visão Geral'?'Visão Geral Executiva':'Dashboard Executivo'}</h2><h3>Acompanhamento integrado de Utilizado, Faturado e Recebido.</h3></div><div className="header-actions">{activeData&&<div className="base-status"><i/><span>Base {activeModule}<strong>{activeData.rows.length.toLocaleString('pt-BR')} registros</strong></span></div>}<div className="updated"><Clock3/><span>Última atualização do {activeModule}<strong>{activeData?activeData.updated.toLocaleString('pt-BR'):'Informação não disponível na base de dados'}</strong></span></div>{admin&&<><button className="icon-button" aria-label="Atualizar módulo ativo" onClick={()=>openUpload(activeModule==='Visão Geral'?null:activeModule)}><RefreshCw/></button><button className="primary-button" onClick={()=>openUpload(null)}><Upload/> Atualizar base</button><button className="secondary-button" onClick={openHistory}><History/> Histórico de importações</button></>}<button className="secondary-button" onClick={()=>{setSharedFilters({});setResetSignal(v=>v+1)}}><Eraser/> Limpar filtros</button>{admin&&<button className="icon-button" aria-label="Sair" onClick={async()=>{await signOut();location.replace('/login')}}><LogOut/></button>}</div></header>
 <nav className="module-nav"><button className={activeModule==='Visão Geral'?'active':''} onClick={()=>setActiveModule('Visão Geral')}><LayoutDashboard/>Visão Geral<span>Executiva</span></button>{modules.map(m=><button key={m} className={activeModule===m?'active':''} onClick={()=>setActiveModule(m)}><Database/>{m}<span>{moduleData[m]?'Disponível':'Sem base'}</span></button>)}</nav>
 {notice&&<button className="version-notice" onClick={()=>setNotice('')}>{notice}</button>}{admin&&<section className="admin-strip"><div><strong>Status das bases</strong><span>{modules.map(m=>`${m}: ${moduleData[m]?'publicada':'sem publicação'}`).join(' • ')}</span></div><button className="secondary-button" onClick={openHistory}><History/> Última atualização</button><button className="primary-button" disabled={!readyImport||loading} onClick={publish}><Send/> Publicar atualização</button></section>}
 {activeModule==='Visão Geral'?<ExecutiveOverview data={moduleData} onOpenModule={setActiveModule} onFiltersChange={setSharedFilters} resetSignal={resetSignal}/>:activeData?<Dashboard rows={activeData.rows} columns={activeData.columns} resetSignal={resetSignal} module={activeModule} sharedFilters={sharedFilters} onSharedFiltersChange={setSharedFilters}/>:<EmptyState module={activeModule} onUpload={admin?()=>openUpload(activeModule):undefined}/>}<footer>UFR Intelligence <span>•</span> Dados exibidos exclusivamente a partir da base publicada</footer>
 {admin&&<UploadModal open={modal} targetModule={activeUploadModule} report={pending?.report??null} loading={loading} error={error} progress={progress} onClose={()=>{if(!loading){setModal(false);setPending(null)}}} onSelectModule={setActiveUploadModule} onFile={chooseFile} onConfirm={confirm}/>} {admin&&showHistory&&<div className="modal-backdrop"><section className="modal history-modal"><div className="modal-header"><div><p className="eyebrow">AUDITORIA</p><h2>Histórico de importações</h2></div><button className="icon-button" onClick={()=>setShowHistory(false)}>×</button></div><div className="history-list">{history.map(h=><article key={h.id}><div><strong>{h.module} • {h.file_name}</strong><span>{new Date(h.created_at).toLocaleString('pt-BR')} • {h.row_count.toLocaleString('pt-BR')} registros • {h.status}</span>{h.error_message&&<small>{h.error_message}</small>}</div><button className="secondary-button" disabled={h.is_active||h.status!=='publicado'||loading} onClick={()=>restore(h.id)}><RotateCcw/> Restaurar versão</button></article>)}</div></section></div>}</div>;
}
const path=location.pathname.replace(/\/$/,'')||'/'; if(path==='/login')createRoot(document.getElementById('root')!).render(<StrictMode><Login/></StrictMode>); else if(path==='/admin'||path==='/dashboard')createRoot(document.getElementById('root')!).render(<StrictMode><App admin={path==='/admin'}/></StrictMode>); else location.replace('/dashboard');
