import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Clock3, Database, Eraser, LayoutDashboard, RefreshCw, Upload } from 'lucide-react';
import { Dashboard } from './components/Dashboard';
import { ExecutiveOverview, type OverviewModuleData } from './components/ExecutiveOverview';
import { EmptyState } from './components/EmptyState';
import { UploadModal } from './components/UploadModal';
import { inspectWorkbook, UTILIZADO_SCHEMA_VERSION } from './services/workbook';
import { loadPersistentBases, persistBase } from './services/persistentStore';
import type { DataRow, SourceModule, ValidationReport } from './types';
import './styles.css';

export function App() {
  const [moduleData, setModuleData] = useState<Partial<Record<SourceModule, OverviewModuleData>>>({}); const [moduleStatus, setModuleStatus] = useState<Partial<Record<SourceModule, string>>>({}); const [activeModule, setActiveModule] = useState<SourceModule | 'Visão Geral'>('Visão Geral'); const [activeUploadModule, setActiveUploadModule] = useState<SourceModule|null>(null); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string|null>(null); const [pending, setPending] = useState<{rows:DataRow[];report:ValidationReport}|null>(null); const [pendingFile, setPendingFile] = useState<File|null>(null); const [sharedFilters, setSharedFilters] = useState<Record<string, string[]>>({}); const [adminSession, setAdminSession] = useState(() => !!sessionStorage.getItem('ufr-admin-token')); const [resetSignal, setResetSignal] = useState(0);
  useEffect(() => { loadPersistentBases().then((stored) => { setModuleData(stored); setModuleStatus(Object.fromEntries(Object.keys(stored).map((module) => [module, 'Disponível']))); }).catch(() => undefined); }, []);
  useEffect(() => { const key = 'ufr-utilizado-schema'; if (localStorage.getItem(key) !== UTILIZADO_SCHEMA_VERSION) { localStorage.removeItem('ufr-active-filters'); localStorage.setItem(key, UTILIZADO_SCHEMA_VERSION); setResetSignal((value) => value + 1); } }, []);
  const chooseFile = async (file: File) => { setError(null); if (!activeUploadModule) { setError('Selecione qual base deseja atualizar antes de escolher o arquivo.'); return; } setModuleStatus((current) => ({ ...current, [activeUploadModule]: 'Validando' })); setLoading(true); try { if (!file.name.toLowerCase().endsWith('.xlsx')) throw new Error('O formato do arquivo não é suportado. Selecione exclusivamente um arquivo .xlsx.'); const inspected = await inspectWorkbook(file, activeUploadModule); setPending(inspected); setPendingFile(file); setModuleStatus((current) => ({ ...current, [activeUploadModule]: 'Processando' })); } catch (reason) { setModuleStatus((current) => ({ ...current, [activeUploadModule]: 'Erro na importação' })); setError(reason instanceof Error ? reason.message : 'O arquivo não pôde ser lido. A base existente foi preservada; nenhuma alteração foi realizada.'); } finally { setLoading(false); } };
  const confirm = async () => { if (!pending || !pendingFile) return; const module = pending.report.module; const user = sessionStorage.getItem('ufr-admin-user') ?? window.prompt('Identificação do administrador:')?.trim(); const adminToken = sessionStorage.getItem('ufr-admin-token') ?? window.prompt('Token de administrador:')?.trim(); if (!user || !adminToken) { setError('A atualização foi cancelada. Somente administradores autorizados podem substituir bases.'); return; } sessionStorage.setItem('ufr-admin-user', user); sessionStorage.setItem('ufr-admin-token', adminToken); setLoading(true); try { const persisted = await persistBase({ module, rows: pending.rows, columns: pending.report.columns, report: pending.report, file: pendingFile, user, adminToken }); setModuleData((current) => ({ ...current, [module]: persisted })); setModuleStatus((current) => ({ ...current, [module]: 'Disponível' })); setActiveModule(module); setResetSignal((value) => value + 1); setModal(false); setPending(null); setPendingFile(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível persistir a base. A versão anterior foi preservada.'); } finally { setLoading(false); } };
  const authenticate = () => { const user = window.prompt('Identificação do administrador:')?.trim(); const token = window.prompt('Token de administrador:')?.trim(); if (!user || !token) return; sessionStorage.setItem('ufr-admin-user', user); sessionStorage.setItem('ufr-admin-token', token); setAdminSession(true); };
  const openUpload = (module: SourceModule | null = null) => { setPending(null); setError(null); setActiveUploadModule(module); setModal(true); };
  const closeUpload = () => { if (activeUploadModule) setModuleStatus((current) => ({ ...current, [activeUploadModule]: moduleData[activeUploadModule] ? 'Disponível' : 'Sem base' })); setModal(false); setPending(null); setPendingFile(null); setError(null); };
  const activeData = activeModule === 'Visão Geral' ? undefined : moduleData[activeModule];
  return <div className="app-shell">
    <header><div className="brand-mark">UFR</div><div className="heading"><p>INTELIGÊNCIA EXECUTIVA</p><h1>Utilizado <i/> <span>Faturado</span> <i/> <span>Recebido</span></h1><h2>{activeModule === 'Visão Geral' ? 'Visão Geral Executiva' : 'Dashboard Executivo'}</h2><h3>Acompanhamento integrado de Utilizado, Faturado e Recebido.</h3></div><div className="header-actions">{activeData && <div className="base-status"><i/><span>Base {activeModule}<strong>{activeData.rows.length.toLocaleString('pt-BR')} registros</strong></span></div>}<div className="updated"><Clock3/><span>Última atualização do {activeModule}<strong>{activeData ? `${activeData.updated.toLocaleString('pt-BR')}${activeData.updatedBy ? ` • por ${activeData.updatedBy}` : ''}` : 'Informação não disponível na base de dados'}</strong></span></div>{adminSession && <button className="icon-button" aria-label="Atualizar módulo ativo" onClick={() => openUpload(activeModule === 'Visão Geral' ? null : activeModule)}><RefreshCw/></button>}<button className="secondary-button" onClick={() => { setSharedFilters({}); setResetSignal((value) => value + 1); }}><Eraser/> Limpar filtros</button>{adminSession ? <button className="primary-button" onClick={() => openUpload(null)}><Upload/> Atualizar base</button> : <button className="secondary-button" onClick={authenticate}>Acesso administrativo</button>}</div></header>
    <nav className="module-nav"><button className={activeModule === 'Visão Geral' ? 'active' : ''} onClick={() => setActiveModule('Visão Geral')}><LayoutDashboard/>Visão Geral<span>Executiva</span></button><button className={activeModule === 'Utilizado' ? 'active' : ''} onClick={() => setActiveModule('Utilizado')}><Database/>Utilizado<span>{moduleStatus.Utilizado ?? (moduleData.Utilizado ? 'Disponível' : 'Sem base')}</span></button><button className={activeModule === 'Faturado' ? 'active' : ''} onClick={() => setActiveModule('Faturado')}><Database/>Faturado<span>{moduleStatus.Faturado ?? (moduleData.Faturado ? 'Disponível' : 'Sem base')}</span></button><button className={activeModule === 'Recebido' ? 'active' : ''} onClick={() => setActiveModule('Recebido')}><Database/>Recebido<span>{moduleStatus.Recebido ?? (moduleData.Recebido ? 'Disponível' : 'Sem base')}</span></button></nav>
    {activeModule === 'Visão Geral' ? <ExecutiveOverview data={moduleData} onOpenModule={setActiveModule} onFiltersChange={setSharedFilters} resetSignal={resetSignal}/> : activeData ? <Dashboard rows={activeData.rows} columns={activeData.columns} resetSignal={resetSignal} module={activeModule} sharedFilters={sharedFilters} onSharedFiltersChange={setSharedFilters}/> : <EmptyState module={activeModule} onUpload={() => adminSession ? openUpload(activeModule) : authenticate()}/>}<footer>UFR Intelligence <span>•</span> Dados exibidos exclusivamente a partir da base importada</footer>
    <UploadModal open={modal} targetModule={activeUploadModule} report={pending?.report??null} loading={loading} error={error} onClose={closeUpload} onSelectModule={setActiveUploadModule} onFile={chooseFile} onConfirm={confirm}/>
  </div>;
}

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
