create extension if not exists pgcrypto;
create type public.import_status as enum ('validando','aguardando confirmação','processando','validando importação','pronto para publicar','publicado','cancelado','erro');
create table public.usuarios (id uuid primary key default gen_random_uuid(), auth_user_id uuid unique not null references auth.users(id) on delete cascade, role text not null check (role in ('admin','viewer')), created_at timestamptz not null default now());
create table public.importacoes (id uuid primary key, module text not null check (module in ('Utilizado','Faturado','Recebido')), file_name text not null, user_id uuid not null, created_at timestamptz not null default now(), published_at timestamptz, row_count bigint not null, stored_row_count bigint, column_count integer not null, total_value numeric, period_start date, period_end date, zero_values bigint not null default 0, negative_values bigint not null default 0, invalid_fields bigint not null default 0, rejected_records bigint not null default 0, expected_batches integer not null, processed_batches integer not null default 0, status public.import_status not null, version_id uuid unique not null, is_active boolean not null default false, error_message text, summary jsonb not null);
create unique index one_active_import_per_module on public.importacoes(module) where is_active;
create or replace function public.create_module_table(table_name text) returns void language plpgsql as $$ begin execute format('create table public.%I (id bigint generated always as identity primary key, module text not null, import_id uuid not null references public.importacoes(id), version_id uuid not null, is_active boolean not null default false, batch_number integer not null, row_number bigint not null, data jsonb not null, unique(import_id,row_number))', table_name); execute format('create index %I on public.%I(version_id,is_active,row_number)', table_name || '_active_idx', table_name); end $$;
select public.create_module_table('utilizado'); select public.create_module_table('faturado'); select public.create_module_table('recebido'); drop function public.create_module_table(text);
alter table public.usuarios enable row level security; alter table public.importacoes enable row level security; alter table public.utilizado enable row level security; alter table public.faturado enable row level security; alter table public.recebido enable row level security;
create or replace function public.activate_import(target_id uuid, require_ready boolean default true) returns void language plpgsql security definer set search_path=public as $$ declare item public.importacoes%rowtype; begin select * into item from public.importacoes where id=target_id for update; if not found or (require_ready and item.status <> 'pronto para publicar') or (not require_ready and item.status <> 'publicado') then raise exception 'Versão indisponível para ativação'; end if; if item.module='Utilizado' then update utilizado set is_active=false where is_active; update utilizado set is_active=true where version_id=item.version_id; elsif item.module='Faturado' then update faturado set is_active=false where is_active; update faturado set is_active=true where version_id=item.version_id; else update recebido set is_active=false where is_active; update recebido set is_active=true where version_id=item.version_id; end if; update importacoes set is_active=false where module=item.module and is_active; update importacoes set is_active=true, status='publicado', published_at=case when require_ready then now() else published_at end where id=item.id; end $$;
revoke all on function public.activate_import(uuid,boolean) from public, anon, authenticated;
-- No table is exposed directly to anonymous clients. Vercel server functions use the service role.
-- After creating the sole administrator in Supabase Auth, authorize it once:
-- insert into public.usuarios(auth_user_id, role) values ('AUTH_USER_UUID', 'admin');
